### ISSUE TITLE
Issue with loading info only popping up with opening url

### ISSUE THREAD

**Issue by ire4ever1190** [ire4ever1190/app4flask#7]
when going the the url for /list I get this error
```
Traceback (most recent call last):
  File "D:\Software\Python 3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Software\Python 3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Software\Python 3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Software\Python 3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\Software\Python 3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Software\Python 3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:/Projects/app4flaskbackend/app4flask.py", line 132, in show_info
    classes.append("<class>" + str(get(today, i, studentnum)) + "</class>")
  File "D:/Projects/app4flaskbackend/app4flask.py", line 121, in get
    parse = jsonstr["class"]
TypeError: 'NoneType' object is not subscriptable
```
but when I run
 ```
show_info(*with args) 
```
In the script instead of 
```
app.run()
```
The error doesn't pop up

**Comment by John-AZ1** [comment]
jsonstr is not return a dictionary. That’s what subscriptable means. You need to ensure jsonstr is still a soup object.

**Comment by ire4ever1190** [comment]
Why does it need to be a soup object? The line of issue should return a json string from the db but instead why run by using the flask decorator it returns none

**Comment by ire4ever1190** [comment]
Dont know what caused the issue but I seemed to have fixed it pushing new code now
